'use strict';
const TOOL='link-boxes',VERSION=1,K={data:'linkBoxes.data.v1',backup:'linkBoxes.lastBackup'};
let state=load(),currentBoxId=null,boxEdit=false,linkEdit=false,importSession=null;
const $=id=>document.getElementById(id);
function blank(){return {boxes:[],links:[]}}
function load(){try{const x=JSON.parse(localStorage.getItem(K.data)||'null');return x&&Array.isArray(x.boxes)&&Array.isArray(x.links)?x:blank()}catch{return blank()}}
function save(){normalizeOrders();localStorage.setItem(K.data,JSON.stringify(state));render()}
function uuid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}-${Math.random().toString(16).slice(2)}`}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function validUrl(s){try{const u=new URL(s);return u.protocol==='http:'||u.protocol==='https:'}catch{return false}}
function fmt(iso){return new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short'}).format(new Date(iso))}
function localDate(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function normalizeOrders(){state.boxes.sort((a,b)=>(a.order??999999)-(b.order??999999)).forEach((x,i)=>x.order=i);for(const b of state.boxes)state.links.filter(x=>x.boxId===b.id).sort((a,c)=>(a.order??999999)-(c.order??999999)).forEach((x,i)=>x.order=i)}
function orderedBoxes(){return [...state.boxes].sort((a,b)=>a.order-b.order)} function boxLinks(id){return state.links.filter(x=>x.boxId===id).sort((a,b)=>a.order-b.order)}
function render(){renderHome();if(currentBoxId)renderBox();updateBackup()}
function renderHome(){$('boxCount').textContent=`${state.boxes.length}箱 ／ ${state.links.length}リンク`;$('homeEmpty').classList.toggle('hidden',state.boxes.length>0);$('toggleBoxEdit').textContent=boxEdit?'完了':'編集';$('boxes').innerHTML=orderedBoxes().map((b,i)=>`<article class="box"><button class="box-open" data-open-box="${esc(b.id)}"><div class="box-title">${esc(b.icon||'📦')} ${esc(b.name)}</div><div class="box-meta">${boxLinks(b.id).length}件</div></button><div class="manage ${boxEdit?'':'hidden'}"><div class="manage-row"><div class="order-actions"><button data-box-move="top" data-id="${esc(b.id)}" title="最上部へ">⇈</button><button data-box-move="up" data-id="${esc(b.id)}">↑</button><button data-box-move="down" data-id="${esc(b.id)}">↓</button><button data-box-move="bottom" data-id="${esc(b.id)}" title="最下部へ">⇊</button></div><div><button data-box-edit="${esc(b.id)}">編集</button> <button data-box-delete="${esc(b.id)}">削除</button></div></div></div></article>`).join('')}
function renderBox(){const b=state.boxes.find(x=>x.id===currentBoxId);if(!b){showHome();return}const list=boxLinks(b.id);$('boxHeading').textContent=`${b.icon||'📦'} ${b.name}`;$('linkCount').textContent=`${list.length}件`;$('linkEmpty').classList.toggle('hidden',list.length>0);$('toggleLinkEdit').textContent=linkEdit?'完了':'編集';$('cards').innerHTML=list.map(c=>`<article class="card"><div class="card-top" data-open-link="${esc(c.id)}" role="link" tabindex="0"><div class="card-title">${esc(c.title||c.url)}</div>${c.title?`<div class="card-url">${esc(c.url)}</div>`:''}</div><div class="card-body"><div class="memo">${esc(c.memo)}</div><div class="meta">登録 ${esc(fmt(c.createdAt))}${c.updatedAt!==c.createdAt?` ／ 更新 ${esc(fmt(c.updatedAt))}`:''}</div><div class="manage ${linkEdit?'':'hidden'}"><div class="manage-row"><div class="order-actions"><button data-link-move="top" data-id="${esc(c.id)}">⇈</button><button data-link-move="up" data-id="${esc(c.id)}">↑</button><button data-link-move="down" data-id="${esc(c.id)}">↓</button><button data-link-move="bottom" data-id="${esc(c.id)}">⇊</button></div><div><button data-link-edit="${esc(c.id)}">編集</button> <button data-link-delete="${esc(c.id)}">削除</button></div></div></div></div></article>`).join('')}
function updateBackup(){const v=localStorage.getItem(K.backup);$('backupStatus').textContent='最終JSON書き出し：'+(v?fmt(v):'まだありません')}
function showHome(){currentBoxId=null;linkEdit=false;$('boxView').classList.add('hidden');$('homeView').classList.remove('hidden');renderHome()}
function showBox(id){currentBoxId=id;boxEdit=false;$('homeView').classList.add('hidden');$('boxView').classList.remove('hidden');renderBox()}
$('newBox').onclick=()=>openBoxDialog();$('toggleBoxEdit').onclick=()=>{boxEdit=!boxEdit;renderHome()};$('backHome').onclick=showHome;$('toggleLinkEdit').onclick=()=>{linkEdit=!linkEdit;renderBox()};
function openBoxDialog(b=null){$('boxDialogTitle').textContent=b?'箱を編集':'箱を作る';$('boxEditId').value=b?.id||'';$('boxIcon').value=b?.icon||'';$('boxName').value=b?.name||'';$('boxDialog').showModal()}
$('boxForm').onsubmit=e=>{e.preventDefault();const id=$('boxEditId').value,name=$('boxName').value.trim(),icon=$('boxIcon').value.trim();if(!name)return;if(id){const b=state.boxes.find(x=>x.id===id);if(b){b.name=name;b.icon=icon}}else state.boxes.push({id:uuid(),icon,name,order:state.boxes.length});$('boxDialog').close();save()};
document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>$(x.dataset.close).close());
$('boxes').onclick=e=>{const open=e.target.closest('[data-open-box]'),edit=e.target.closest('[data-box-edit]'),del=e.target.closest('[data-box-delete]'),mv=e.target.closest('[data-box-move]');if(boxEdit&&open)return;if(edit){openBoxDialog(state.boxes.find(x=>x.id===edit.dataset.boxEdit));return}if(del){deleteBox(del.dataset.boxDelete);return}if(mv){moveItem(state.boxes,mv.dataset.id,mv.dataset.boxMove);save();return}if(open)showBox(open.dataset.openBox)};
function moveItem(list,id,dir){const a=[...list].sort((x,y)=>x.order-y.order),i=a.findIndex(x=>x.id===id);if(i<0)return;const [x]=a.splice(i,1);let n=i;if(dir==='up')n=Math.max(0,i-1);if(dir==='down')n=Math.min(a.length,i+1);if(dir==='top')n=0;if(dir==='bottom')n=a.length;a.splice(n,0,x);a.forEach((v,j)=>v.order=j)}
function deleteBox(id){const b=state.boxes.find(x=>x.id===id);if(!b)return;const n=boxLinks(id).length;if(!n){if(confirm(`「${b.name}」を削除しますか？`)){state.boxes=state.boxes.filter(x=>x.id!==id);save()}return}const choice=prompt(`この箱には${n}件のリンクがあります。\n\n1 = HTMLとして保存してから削除\n2 = 保存せず箱と中身を削除\nそれ以外 = キャンセル`);if(choice==='1'){exportBoxHtml(id);if(confirm('HTML書き出し処理を実行しました。ファイル保存を確認できる状態で、箱と中身を削除しますか？'))removeBox(id)}else if(choice==='2'&&confirm(`${n}件のリンクごと削除します。よろしいですか？`))removeBox(id)}
function removeBox(id){state.links=state.links.filter(x=>x.boxId!==id);state.boxes=state.boxes.filter(x=>x.id!==id);if(currentBoxId===id)showHome();save()}
$('newLink').onclick=()=>openLinkDialog();function fillBoxSelect(selected){$('linkBox').innerHTML=orderedBoxes().map(b=>`<option value="${esc(b.id)}" ${b.id===selected?'selected':''}>${esc(b.icon||'📦')} ${esc(b.name)}</option>`).join('')}
function openLinkDialog(c=null){$('linkDialogTitle').textContent=c?'リンク編集':'リンク追加';$('linkEditId').value=c?.id||'';$('linkUrl').value=c?.url||'';$('linkTitle').value=c?.title||'';$('linkMemo').value=c?.memo||'';fillBoxSelect(c?.boxId||currentBoxId);$('linkError').textContent='';$('linkDialog').showModal()}
$('linkForm').onsubmit=e=>{e.preventDefault();const id=$('linkEditId').value,url=$('linkUrl').value.trim(),title=$('linkTitle').value.trim(),memo=$('linkMemo').value.trim(),boxId=$('linkBox').value;if(!validUrl(url)){$('linkError').textContent='URLは http:// または https:// の有効なURLにしてください。';return}const now=new Date().toISOString();if(id){const c=state.links.find(x=>x.id===id);if(c){const moved=c.boxId!==boxId;c.url=url;c.title=title;c.memo=memo;c.updatedAt=now;if(moved){c.boxId=boxId;c.order=boxLinks(boxId).length}}}else state.links.push({id:uuid(),url,title,memo,boxId,order:boxLinks(boxId).length,createdAt:now,updatedAt:now});$('linkDialog').close();save()};
$('cards').onclick=e=>{const open=e.target.closest('[data-open-link]'),edit=e.target.closest('[data-link-edit]'),del=e.target.closest('[data-link-delete]'),mv=e.target.closest('[data-link-move]');if(linkEdit&&open)return;if(edit){openLinkDialog(state.links.find(x=>x.id===edit.dataset.linkEdit));return}if(del){const c=state.links.find(x=>x.id===del.dataset.linkDelete);if(c&&confirm('このリンクを削除しますか？')){state.links=state.links.filter(x=>x.id!==c.id);save()}return}if(mv){moveItem(state.links.filter(x=>x.boxId===currentBoxId),mv.dataset.id,mv.dataset.linkMove);save();return}if(open){const c=state.links.find(x=>x.id===open.dataset.openLink);if(c)window.open(c.url,'_blank','noopener,noreferrer')}};
$('cards').onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-open-link]')){e.preventDefault();e.target.click()}};
function download(name,text,type){const blob=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
$('exportJson').onclick=()=>{const now=new Date().toISOString();download(`link-boxes-${localDate()}.json`,JSON.stringify({formatVersion:VERSION,tool:TOOL,exportedAt:now,boxes:state.boxes,links:state.links},null,2),'application/json');localStorage.setItem(K.backup,now);updateBackup()};
function normBox(b){return {id:String(b.id||''),icon:String(b.icon||''),name:String(b.name||''),order:Number.isFinite(+b.order)?+b.order:999999}}
function normLink(c){return {id:String(c.id||''),url:String(c.url||''),title:String(c.title||''),memo:String(c.memo||''),boxId:String(c.boxId||''),order:Number.isFinite(+c.order)?+c.order:999999,createdAt:String(c.createdAt||''),updatedAt:String(c.updatedAt||'')}}
function eqBox(a,b){return a.icon===b.icon&&a.name===b.name} function eqLink(a,b){return ['url','title','memo','boxId','createdAt','updatedAt'].every(k=>(a[k]||'')===(b[k]||''))}
$('importJson').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{const d=JSON.parse(await f.text());if(d.tool!==TOOL){alert(`部屋が違います！\nこのJSONは「${d.tool||'不明'}」用です。`);return}if(d.formatVersion!==VERSION||!Array.isArray(d.boxes)||!Array.isArray(d.links))throw Error();const boxes=d.boxes.map(normBox).filter(b=>b.id&&b.name),links=d.links.map(normLink).filter(c=>c.id&&c.boxId&&validUrl(c.url));if(links.length!==d.links.length){alert('読み込みデータに不正なリンクがあります。');return}importSession={boxes,links,map:new Map(),boxConflicts:[],linkConflicts:[],addedBoxes:0,addedLinks:0,same:0};for(const b of boxes){const cur=state.boxes.find(x=>x.id===b.id);if(!cur){state.boxes.push({...b,order:state.boxes.length});importSession.map.set(b.id,b.id);importSession.addedBoxes++}else if(eqBox(cur,b)){importSession.map.set(b.id,b.id);importSession.same++}else importSession.boxConflicts.push({kind:'box',cur,inc:b})}save();continueImportBoxes()}catch{alert('JSONを読み込めませんでした。ファイル内容を確認してください。')}};
function continueImportBoxes(){if(importSession.boxConflicts.length){showMerge(importSession.boxConflicts.shift());return}for(const c0 of importSession.links){const mapped=importSession.map.get(c0.boxId);if(!mapped)continue;const c={...c0,boxId:mapped};const cur=state.links.find(x=>x.id===c.id);if(!cur){state.links.push({...c,order:boxLinks(mapped).length});importSession.addedLinks++}else if(eqLink(cur,c))importSession.same++;else importSession.linkConflicts.push({kind:'link',cur,inc:c})}save();continueImportLinks()}
function continueImportLinks(){if(importSession.linkConflicts.length){showMerge(importSession.linkConflicts.shift());return}const s=importSession;importSession=null;save();alert(`読み込み完了：箱${s.addedBoxes}件、リンク${s.addedLinks}件を追加。${s.same}件は同一内容のため変更なし。`)}
let activeConflict=null;function showMerge(x){activeConflict=x;$('mergeProgress').textContent=x.kind==='box'?'箱の衝突です。読み込み側のカード所属も選択結果に追従します。':'リンクの衝突です。';$('currentItem').innerHTML=compare(x.cur,x.kind);$('incomingItem').innerHTML=compare(x.inc,x.kind);$('mergeDialog').showModal()}
function compare(x,kind){if(kind==='box')return `<dl><dt>アイコン</dt><dd>${esc(x.icon||'（なし）')}</dd><dt>箱名</dt><dd>${esc(x.name)}</dd></dl>`;return `<dl><dt>タイトル</dt><dd>${esc(x.title||'（なし）')}</dd><dt>URL</dt><dd>${esc(x.url)}</dd><dt>メモ</dt><dd>${esc(x.memo||'（なし）')}</dd></dl>`}
$('mergeDialog').onclick=e=>{const b=e.target.closest('[data-choice]');if(!b||!activeConflict)return;const x=activeConflict,choice=b.dataset.choice;if(x.kind==='box'){if(choice==='current')importSession.map.set(x.inc.id,x.cur.id);if(choice==='incoming'){Object.assign(x.cur,{icon:x.inc.icon,name:x.inc.name});importSession.map.set(x.inc.id,x.cur.id)}if(choice==='both'){const nid=uuid();state.boxes.push({...x.inc,id:nid,order:state.boxes.length});importSession.map.set(x.inc.id,nid);importSession.addedBoxes++}}else{const i=state.links.findIndex(c=>c.id===x.cur.id);if(choice==='incoming')state.links[i]={...x.inc,order:x.cur.order};if(choice==='both'){state.links.push({...x.inc,id:uuid(),order:boxLinks(x.inc.boxId).length});importSession.addedLinks++}}$('mergeDialog').close();activeConflict=null;save();x.kind==='box'?continueImportBoxes():continueImportLinks()};
$('exportHtml').onclick=()=>currentBoxId&&exportBoxHtml(currentBoxId);function exportBoxHtml(id){const b=state.boxes.find(x=>x.id===id);if(!b)return;const list=boxLinks(id),items=list.map(c=>`<article><h2><a href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">${esc(c.title||c.url)}</a></h2>${c.title?`<p class="url"><a href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">${esc(c.url)}</a></p>`:''}${c.memo?`<p class="memo">${esc(c.memo)}</p>`:''}</article>`).join('');const html=`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(b.name)}</title><style>body{font-family:system-ui,sans-serif;max-width:900px;margin:40px auto;padding:0 18px;line-height:1.6;color:#292722}article{padding:18px 0;border-bottom:1px solid #ddd}h2{font-size:1.15rem;margin:0}.url{font-size:.85rem;color:#777;overflow-wrap:anywhere}.memo{white-space:pre-wrap}a{color:#245f78}</style></head><body><h1>${esc(b.icon||'📦')} ${esc(b.name)}</h1><p>書き出し：${esc(fmt(new Date().toISOString()))} ／ ${list.length}件</p>${items}</body></html>`;download(`link-box-${localDate()}.html`,html,'text/html')}
$('resetAll').onclick=()=>{if(!state.boxes.length&&!state.links.length)return;if(confirm(`箱${state.boxes.length}個・リンク${state.links.length}件をすべて削除します。\nこの操作は元に戻せません。よろしいですか？`)){state=blank();showHome();save()}};
if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});render();
